# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniele/devel/libmelter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniele/devel/libmelter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniele/devel/libmelter/CMakeFiles /home/daniele/devel/libmelter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniele/devel/libmelter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named melter

# Build rule for target.
melter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 melter
.PHONY : melter

# fast build rule for target.
melter/fast:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/build
.PHONY : melter/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

BufferObserver.o: BufferObserver.cc.o
.PHONY : BufferObserver.o

# target to build an object file
BufferObserver.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/BufferObserver.cc.o
.PHONY : BufferObserver.cc.o

BufferObserver.i: BufferObserver.cc.i
.PHONY : BufferObserver.i

# target to preprocess a source file
BufferObserver.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/BufferObserver.cc.i
.PHONY : BufferObserver.cc.i

BufferObserver.s: BufferObserver.cc.s
.PHONY : BufferObserver.s

# target to generate assembly for a file
BufferObserver.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/BufferObserver.cc.s
.PHONY : BufferObserver.cc.s

Chunk.o: Chunk.cc.o
.PHONY : Chunk.o

# target to build an object file
Chunk.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Chunk.cc.o
.PHONY : Chunk.cc.o

Chunk.i: Chunk.cc.i
.PHONY : Chunk.i

# target to preprocess a source file
Chunk.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Chunk.cc.i
.PHONY : Chunk.cc.i

Chunk.s: Chunk.cc.s
.PHONY : Chunk.s

# target to generate assembly for a file
Chunk.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Chunk.cc.s
.PHONY : Chunk.cc.s

IOAppend.o: IOAppend.cc.o
.PHONY : IOAppend.o

# target to build an object file
IOAppend.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOAppend.cc.o
.PHONY : IOAppend.cc.o

IOAppend.i: IOAppend.cc.i
.PHONY : IOAppend.i

# target to preprocess a source file
IOAppend.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOAppend.cc.i
.PHONY : IOAppend.cc.i

IOAppend.s: IOAppend.cc.s
.PHONY : IOAppend.s

# target to generate assembly for a file
IOAppend.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOAppend.cc.s
.PHONY : IOAppend.cc.s

IOBuffer.o: IOBuffer.cc.o
.PHONY : IOBuffer.o

# target to build an object file
IOBuffer.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOBuffer.cc.o
.PHONY : IOBuffer.cc.o

IOBuffer.i: IOBuffer.cc.i
.PHONY : IOBuffer.i

# target to preprocess a source file
IOBuffer.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOBuffer.cc.i
.PHONY : IOBuffer.cc.i

IOBuffer.s: IOBuffer.cc.s
.PHONY : IOBuffer.s

# target to generate assembly for a file
IOBuffer.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOBuffer.cc.s
.PHONY : IOBuffer.cc.s

IOComplete.o: IOComplete.cc.o
.PHONY : IOComplete.o

# target to build an object file
IOComplete.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOComplete.cc.o
.PHONY : IOComplete.cc.o

IOComplete.i: IOComplete.cc.i
.PHONY : IOComplete.i

# target to preprocess a source file
IOComplete.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOComplete.cc.i
.PHONY : IOComplete.cc.i

IOComplete.s: IOComplete.cc.s
.PHONY : IOComplete.s

# target to generate assembly for a file
IOComplete.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOComplete.cc.s
.PHONY : IOComplete.cc.s

IOFlush.o: IOFlush.cc.o
.PHONY : IOFlush.o

# target to build an object file
IOFlush.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOFlush.cc.o
.PHONY : IOFlush.cc.o

IOFlush.i: IOFlush.cc.i
.PHONY : IOFlush.i

# target to preprocess a source file
IOFlush.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOFlush.cc.i
.PHONY : IOFlush.cc.i

IOFlush.s: IOFlush.cc.s
.PHONY : IOFlush.s

# target to generate assembly for a file
IOFlush.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOFlush.cc.s
.PHONY : IOFlush.cc.s

IOManager.o: IOManager.cc.o
.PHONY : IOManager.o

# target to build an object file
IOManager.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOManager.cc.o
.PHONY : IOManager.cc.o

IOManager.i: IOManager.cc.i
.PHONY : IOManager.i

# target to preprocess a source file
IOManager.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOManager.cc.i
.PHONY : IOManager.cc.i

IOManager.s: IOManager.cc.s
.PHONY : IOManager.s

# target to generate assembly for a file
IOManager.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOManager.cc.s
.PHONY : IOManager.cc.s

IOOperation.o: IOOperation.cc.o
.PHONY : IOOperation.o

# target to build an object file
IOOperation.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOOperation.cc.o
.PHONY : IOOperation.cc.o

IOOperation.i: IOOperation.cc.i
.PHONY : IOOperation.i

# target to preprocess a source file
IOOperation.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOOperation.cc.i
.PHONY : IOOperation.cc.i

IOOperation.s: IOOperation.cc.s
.PHONY : IOOperation.s

# target to generate assembly for a file
IOOperation.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/IOOperation.cc.s
.PHONY : IOOperation.cc.s

Mangler.o: Mangler.cc.o
.PHONY : Mangler.o

# target to build an object file
Mangler.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Mangler.cc.o
.PHONY : Mangler.cc.o

Mangler.i: Mangler.cc.i
.PHONY : Mangler.i

# target to preprocess a source file
Mangler.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Mangler.cc.i
.PHONY : Mangler.cc.i

Mangler.s: Mangler.cc.s
.PHONY : Mangler.s

# target to generate assembly for a file
Mangler.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Mangler.cc.s
.PHONY : Mangler.cc.s

Melter.o: Melter.cc.o
.PHONY : Melter.o

# target to build an object file
Melter.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Melter.cc.o
.PHONY : Melter.cc.o

Melter.i: Melter.cc.i
.PHONY : Melter.i

# target to preprocess a source file
Melter.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Melter.cc.i
.PHONY : Melter.cc.i

Melter.s: Melter.cc.s
.PHONY : Melter.s

# target to generate assembly for a file
Melter.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/Melter.cc.s
.PHONY : Melter.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/melter.dir/build.make CMakeFiles/melter.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... melter"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... tests"
	@echo "... BufferObserver.o"
	@echo "... BufferObserver.i"
	@echo "... BufferObserver.s"
	@echo "... Chunk.o"
	@echo "... Chunk.i"
	@echo "... Chunk.s"
	@echo "... IOAppend.o"
	@echo "... IOAppend.i"
	@echo "... IOAppend.s"
	@echo "... IOBuffer.o"
	@echo "... IOBuffer.i"
	@echo "... IOBuffer.s"
	@echo "... IOComplete.o"
	@echo "... IOComplete.i"
	@echo "... IOComplete.s"
	@echo "... IOFlush.o"
	@echo "... IOFlush.i"
	@echo "... IOFlush.s"
	@echo "... IOManager.o"
	@echo "... IOManager.i"
	@echo "... IOManager.s"
	@echo "... IOOperation.o"
	@echo "... IOOperation.i"
	@echo "... IOOperation.s"
	@echo "... Mangler.o"
	@echo "... Mangler.i"
	@echo "... Mangler.s"
	@echo "... Melter.o"
	@echo "... Melter.i"
	@echo "... Melter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

